### PR TITLE
Update FcmServiceProvider.php

### PR DESCRIPTION
**Pull request by erlangp**
https://www.php-fig.org/psr/psr-2/#6-closures

### CODE REVIEW

**Comment by erlangp** [comment]
sorry sir, but i suggess to add space because PSR-2
https://www.php-fig.org/psr/psr-2/#6-closures

**Comment by erlangp** [comment]
i use this tool to fixes code to follow standards
https://github.com/FriendsOfPHP/PHP-CS-Fixer
:)

**Comment by mai92** [comment]
thank you so much @erlangp

**Comment by erlangp** [comment]
thanks too for your great lib :+1:

**Pull request merged**
